apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-servico-deployment
  labels:
    app: api-servico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-servico
  template:
    metadata:
      labels:
        app: api-servico
    spec:
      containers:
        - name: api-servico
          image: barbearia-servico:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: api-servico-service
spec:
  type: NodePort
  selector:
    app: api-servico
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090